onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@sentry-internal/node-cpu-profiler'
  - '@tsparticles/engine'
  - esbuild
  - unrs-resolver

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
